package typst

import (
	"embed"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/askrejans/crowdoc/v2/ast"
)

//go:embed assets/crowdoc.typ styles/*.typ
var files embed.FS

// FontSet holds resolved font fallback chains per role.
type FontSet struct {
	Main, Sans, Mono, Math, Heading []string
}

// Options configures rendering.
type Options struct {
	Style *Style
	// TemplateSource replaces the style's Typst source (a custom template
	// defining `template(meta, body)`).
	TemplateSource string
	Lang, Region   string
	Terms          map[string]string
	// Labels gives the text before and after the number in numbered
	// labels per kind (figure, table, listing, chapter, section, appendix).
	Labels    map[string][2]string
	PageOfFmt string // "Page %d of %d"
	Fonts     FontSet
	Unsafe    bool
	Hooks     Hooks
	Generator string
	// Now is used for the generated date when the document has none.
	Now time.Time
	// LocalDate formats a parsed date in the document language.
	LocalDate func(t time.Time) string
}

// Bundle is a self-contained Typst project.
type Bundle struct {
	// Files maps bundle-relative paths to contents (main.typ, crowdoc.typ,
	// style.typ). Image assets are added by the caller.
	Files    map[string][]byte
	Warnings []string
	// Settings are the resolved layout decisions (useful for callers).
	Settings Settings
}

// Settings records resolved layout decisions.
type Settings struct {
	TOC, NumberSections, TitlePage, Signatures bool
	// ShowTitle prints the title block. A title derived from the file name
	// is only printed on a title page unless the document asks for it.
	ShowTitle bool
}

// Render converts doc into a Typst bundle.
func Render(doc *ast.Document, o Options) (*Bundle, error) {
	if o.Style == nil {
		return nil, fmt.Errorf("no style selected")
	}
	styleSrc := o.TemplateSource
	if styleSrc == "" {
		data, err := files.ReadFile("styles/" + o.Style.File)
		if err != nil {
			return nil, fmt.Errorf("style %q: %w", o.Style.Name, err)
		}
		styleSrc = string(data)
	}
	lib, err := files.ReadFile("assets/crowdoc.typ")
	if err != nil {
		return nil, err
	}

	w := &writer{hooks: o.Hooks, labels: collectLabels(doc), unsafe: o.Unsafe}
	w.linksNote = o.Style.LinksAsNotes
	if doc.Meta.LinksAsNotes != nil {
		w.linksNote = *doc.Meta.LinksAsNotes
	}

	settings := resolveSettings(doc, o.Style)
	body := w.blocks(doc.Blocks)
	if !w.bibDone {
		if bib := w.bibliography(); bib != "" {
			body += "\n\n" + bib
		}
	}
	meta := w.metaDict(doc, o, settings)

	var main strings.Builder
	gen := o.Generator
	if gen == "" {
		gen = "crowdoc"
	}
	fmt.Fprintf(&main, "// Generated by %s. Edit the source document instead.\n", gen)
	main.WriteString("#import \"crowdoc.typ\": *\n#import \"style.typ\": template\n")
	main.WriteString("#show: template.with(")
	main.WriteString(meta)
	main.WriteString(")\n\n")
	main.WriteString(body)
	main.WriteString("\n")

	return &Bundle{
		Files: map[string][]byte{
			"main.typ":    []byte(main.String()),
			"crowdoc.typ": lib,
			"style.typ":   []byte(styleSrc),
		},
		Warnings: w.warnings,
		Settings: settings,
	}, nil
}

func collectLabels(doc *ast.Document) map[string]bool {
	labels := map[string]bool{}
	ast.WalkBlocks(doc.Blocks, func(b ast.Block) bool {
		switch n := b.(type) {
		case *ast.Heading:
			labels[n.Attr.ID] = true
		case *ast.Figure:
			if n.Caption != nil || n.Attr.ID != "" {
				labels[n.Attr.ID] = true
			}
		case *ast.Table:
			labels[n.Attr.ID] = true
		case *ast.MathBlock:
			labels[n.Label] = true
		case *ast.CodeBlock:
			labels[n.Attr.ID] = true
		case *ast.Div:
			if calloutKinds[firstClass(n.Attr)] {
				labels[n.Attr.ID] = true
			}
		case *ast.ReferenceList:
			for _, e := range n.Entries {
				labels[e.ID] = true
			}
		}
		return true
	})
	ast.WalkInlines(doc.Blocks, func(in ast.Inline) {
		if sp, ok := in.(*ast.Span); ok && sp.Attr.ID != "" {
			labels[sp.Attr.ID] = true
		}
	})
	delete(labels, "")
	return labels
}

func firstClass(a ast.Attr) string {
	if len(a.Classes) == 0 {
		return ""
	}
	return a.Classes[0]
}

func resolveSettings(doc *ast.Document, st *Style) Settings {
	s := Settings{NumberSections: st.NumberSections, TitlePage: st.TitlePage && !doc.Meta.NoTitlePage}
	if doc.Meta.NumberSections != nil {
		s.NumberSections = *doc.Meta.NumberSections
	}
	if doc.Meta.ShowTitle != nil {
		s.ShowTitle = *doc.Meta.ShowTitle
	} else {
		s.ShowTitle = !doc.Meta.TitleFromName || s.TitlePage
	}
	switch {
	case doc.Meta.TOC != nil:
		s.TOC = *doc.Meta.TOC
	case st.TOC == "always":
		// Even "always" needs something to list: a document without
		// headings (a scanned page, a short note) gets no empty contents.
		ast.WalkBlocks(doc.Blocks, func(b ast.Block) bool {
			if _, ok := b.(*ast.Heading); ok {
				s.TOC = true
			}
			return !s.TOC
		})
	case st.TOC == "auto":
		// A contents page only pays off in a longer document.
		top, words := 0, 0
		for _, b := range doc.Blocks {
			if h, ok := b.(*ast.Heading); ok && h.Level == 1 {
				top++
			}
		}
		ast.WalkBlocks(doc.Blocks, func(b ast.Block) bool {
			if p, ok := b.(*ast.Para); ok {
				words += len(strings.Fields(ast.PlainText(p.Inlines)))
			}
			return true
		})
		s.TOC = (top >= 4 && words >= 1200) || top >= 8
	}
	switch {
	case doc.Meta.Signatures != nil:
		s.Signatures = *doc.Meta.Signatures
	case st.Signatures == "always":
		s.Signatures = true
	case st.Signatures == "auto":
		s.Signatures = looksLikeAgreement(doc.Meta.Title + " " + doc.Meta.DocType)
	}
	return s
}

var agreementRe = regexp.MustCompile(`(?i)agreement|contract|\bnda\b|līgums|ligums|vienošanās|vertrag|contrat|contrato|contratto|umowa|smlouva|sutartis|leping|sopimus|avtal|aftale|overeenkomst|szerződés|sözleşme|договор|угода`)

func looksLikeAgreement(s string) bool { return agreementRe.MatchString(s) }

// ---------------------------------------------------------------------------
// Metadata dictionary
// ---------------------------------------------------------------------------

var lengthRe = regexp.MustCompile(`^\d+(\.\d+)?(pt|mm|cm|in|em)$`)

func (w *writer) metaDict(doc *ast.Document, o Options, s Settings) string {
	m := doc.Meta
	d := &dict{}
	opt := func(v string) string {
		if strings.TrimSpace(v) == "" {
			return "none"
		}
		return textContent(v)
	}
	// title-text always names the PDF; the printed title, subtitle and
	// running title are none when the title block is hidden.
	d.add("title-text", str(m.Title))
	d.add("show-title", boolean(s.ShowTitle))
	if s.ShowTitle {
		d.add("title", textContent(m.Title))
		d.add("subtitle", opt(m.Subtitle))
		d.add("short-title", opt(firstNonEmpty(m.ShortTitle, m.Title)))
	} else {
		d.add("title", "none")
		d.add("subtitle", "none")
		d.add("short-title", "none")
	}

	var authors []string
	for _, a := range m.Authors {
		ad := &dict{}
		ad.add("name", textContent(a.Name))
		affs := make([]string, 0, len(a.Affiliations))
		for _, af := range a.Affiliations {
			affs = append(affs, textContent(af))
		}
		ad.add("affiliations", array(affs))
		ad.add("email", optStr(a.Email))
		ad.add("orcid", optStr(a.ORCID))
		ad.add("corresponding", boolean(a.Corresponding))
		authors = append(authors, ad.String())
	}
	d.add("authors", array(authors))
	d.add("author-names", strArray(m.AuthorNames()))
	org := m.Organization
	d.add("organization", opt(org))
	d.add("issuer", opt(firstNonEmpty(org, strings.Join(m.AuthorNames(), ", "))))

	dateText, pdfDate := w.date(m.Date, o)
	d.add("date", opt(dateText))
	d.add("pdf-date", pdfDate)
	d.add("version", opt(m.Version))
	d.add("status", opt(m.Status))
	d.add("classification", opt(m.Classification))
	d.add("doc-type", str(m.DocType))
	d.add("keywords", strArray(m.Keywords))
	d.add("keywords-content", opt(strings.Join(m.Keywords, ", ")))
	desc := firstNonEmpty(m.Summary, m.Subject)
	if desc == "" && len(m.Abstract) > 0 {
		desc = truncate(ast.BlocksText(m.Abstract), 400)
	}
	d.add("description", optStr(desc))
	d.add("summary", opt(m.Summary))
	if len(m.Abstract) > 0 {
		d.add("abstract", content(w.blocks(m.Abstract)))
	} else {
		d.add("abstract", "none")
	}
	d.add("lang", str(firstNonEmpty(o.Lang, "en")))
	if o.Region != "" {
		d.add("region", str(o.Region))
	} else {
		d.add("region", "none")
	}
	d.add("toc", boolean(s.TOC))
	d.add("lof", boolean(m.LOF))
	d.add("lot", boolean(m.LOT))
	d.add("number-sections", boolean(s.NumberSections))
	d.add("title-page", boolean(s.TitlePage))
	d.add("signatures", boolean(s.Signatures))

	size := o.Style.FontSize
	if m.FontSize > 0 {
		size = float64(m.FontSize)
	}
	d.add("font-size", ftoa(size)+"pt")
	d.add("leading", leadingFor(m.LineSpacing))
	d.add("paper", str(typstPaper(m.Paper, o.Lang)))
	d.add("landscape", boolean(m.Landscape))
	cols := o.Style.Columns
	if m.Columns > 0 {
		cols = m.Columns
	}
	d.add("columns", strconv.Itoa(max(cols, 1)))
	md := &dict{}
	for _, kv := range [][2]string{{"top", m.Margins.Top}, {"bottom", m.Margins.Bottom}, {"left", m.Margins.Left}, {"right", m.Margins.Right}} {
		v := strings.ToLower(strings.TrimSpace(kv[1]))
		if lengthRe.MatchString(v) {
			md.add(kv[0], v)
		} else {
			if v != "" {
				w.warn("margin %q is not a valid length (use e.g. 2.5cm, 25mm, 1in)", kv[1])
			}
			md.add(kv[0], "auto")
		}
	}
	d.add("margins", md.String())
	fd := &dict{}
	fd.add("main", strArray(o.Fonts.Main))
	fd.add("sans", strArray(o.Fonts.Sans))
	fd.add("mono", strArray(o.Fonts.Mono))
	fd.add("math", strArray(o.Fonts.Math))
	fd.add("heading", strArray(firstChain(o.Fonts.Heading, o.Fonts.Sans)))
	d.add("fonts", fd.String())
	d.add("accent", colorValue(m.Accent, w))
	d.add("colors", w.colorsDict(m))
	d.add("header-left", opt(m.HeaderLeft))
	d.add("header-right", opt(m.HeaderRight))
	d.add("footer-left", opt(m.FooterLeft))
	d.add("footer-right", opt(m.FooterRight))
	if m.Logo != "" && w.hooks.Image != nil {
		a := w.hooks.Image(&ast.Image{Src: m.Logo, Alt: "logo"})
		if a.Path != "" {
			d.add("logo", str(a.Path))
		} else {
			w.warn("logo %q: %s", m.Logo, a.Missing)
			d.add("logo", "none")
		}
	} else {
		d.add("logo", "none")
	}
	var parties []string
	for _, p := range m.Parties {
		parties = append(parties, textContent(p))
	}
	d.add("parties", array(parties))
	lines := func(ls []string) string {
		out := make([]string, 0, len(ls))
		for _, l := range ls {
			out = append(out, textContent(l))
		}
		return array(out)
	}
	d.add("recipient", lines(m.Recipient))
	d.add("sender", lines(m.Sender))
	d.add("to", opt(m.To))
	d.add("from", opt(m.From))
	d.add("cc", opt(m.CC))
	d.add("opening", opt(m.Opening))
	d.add("closing", opt(m.Closing))
	d.add("place", opt(m.Place))
	d.add("institution", opt(m.Institution))
	d.add("faculty", opt(m.Faculty))
	d.add("department", opt(m.Department))
	d.add("degree", opt(m.Degree))
	d.add("supervisor", opt(m.Supervisor))
	d.add("location", opt(m.Location))
	d.add("jurisdiction", opt(m.Jurisdiction))
	d.add("seller-country", opt(m.SellerCountryCode))
	d.add("buyer-country", opt(m.BuyerCountryCode))
	d.add("vat-breakdown", opt(m.VATBreakdown))
	d.add("legal-notice", opt(m.LegalNotice))

	td := &dict{}
	keys := make([]string, 0, len(o.Terms))
	for k := range o.Terms {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		td.add(str(k), str(o.Terms[k]))
	}
	d.add("terms", td.String())
	ld := &dict{}
	lkeys := make([]string, 0, len(o.Labels))
	for k := range o.Labels {
		lkeys = append(lkeys, k)
	}
	sort.Strings(lkeys)
	for _, k := range lkeys {
		pp := o.Labels[k]
		ld.add(k, "(n) => ["+escapeMarkup(pp[0], true)+"#n;"+escapeMarkup(pp[1], false)+"]")
	}
	d.add("labels", ld.String())
	d.add("page-of", pageOfClosure(firstNonEmpty(o.PageOfFmt, "%d / %d")))

	ed := &dict{}
	ekeys := make([]string, 0, len(m.Extra))
	for k := range m.Extra {
		ekeys = append(ekeys, k)
	}
	sort.Strings(ekeys)
	for _, k := range ekeys {
		if v := fmt.Sprint(m.Extra[k]); v != "" && !strings.ContainsAny(k, "\"\\") {
			ed.add(str(k), textContent(v))
		}
	}
	d.add("extra", ed.String())
	return d.String()
}

func firstChain(a, b []string) []string {
	if len(a) > 0 {
		return a
	}
	return b
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func optStr(v string) string {
	if strings.TrimSpace(v) == "" {
		return "none"
	}
	return str(v)
}

func truncate(s string, n int) string {
	r := []rune(strings.Join(strings.Fields(s), " "))
	if len(r) <= n {
		return string(r)
	}
	return strings.TrimSpace(string(r[:n])) + "…"
}

// date returns the display date and a Typst datetime for PDF metadata.
func (w *writer) date(raw string, o Options) (string, string) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", "auto"
	}
	for _, layout := range []string{"2006-01-02", "2006-01-02T15:04:05Z07:00", "2006-01-02 15:04", "2006-01-02T15:04"} {
		if t, err := time.Parse(layout, raw); err == nil {
			disp := raw
			if o.LocalDate != nil {
				disp = o.LocalDate(t)
			}
			return disp, fmt.Sprintf("datetime(year: %d, month: %d, day: %d)", t.Year(), int(t.Month()), t.Day())
		}
	}
	return raw, "auto"
}

func leadingFor(spacing string) string {
	s := strings.ToLower(strings.TrimSpace(spacing))
	switch s {
	case "":
		return "none"
	case "single", "1", "1.0":
		return "0.65em"
	case "onehalf", "one-half", "1.5", "1.5x":
		return "1.05em"
	case "double", "2", "2.0", "2x":
		return "1.6em"
	}
	if f, err := strconv.ParseFloat(strings.TrimSuffix(s, "x"), 64); err == nil && f >= 0.8 && f <= 3 {
		return ftoa(0.65+(f-1)*0.95) + "em"
	}
	return "none"
}

// typstPaper maps paper names; letter is the default for US English.
func typstPaper(p, lang string) string {
	switch strings.ToLower(strings.ReplaceAll(strings.TrimSpace(p), " ", "")) {
	case "letter", "us-letter", "usletter", "letterpaper":
		return "us-letter"
	case "legal", "us-legal", "uslegal":
		return "us-legal"
	case "executive", "us-executive":
		return "us-executive"
	case "a3":
		return "a3"
	case "a5":
		return "a5"
	case "a6":
		return "a6"
	case "b5":
		return "iso-b5"
	case "a4", "a4paper":
		return "a4"
	case "":
		l := strings.ToLower(lang)
		if l == "en-us" || l == "en-ca" || l == "es-mx" || l == "en-ph" {
			return "us-letter"
		}
		return "a4"
	}
	return "a4"
}

var hexColorRe = regexp.MustCompile(`^#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$`)

func colorValue(v string, w *writer) string {
	v = strings.TrimSpace(v)
	if v == "" {
		return "none"
	}
	if hexColorRe.MatchString(v) {
		return "rgb(" + str("#"+strings.TrimPrefix(v, "#")) + ")"
	}
	w.warn("accent colour %q is not a hex colour like #6A00FF", v)
	return "none"
}

// colorsDict merges the named palette, individual colour overrides and the
// accent into a Typst dictionary of colours.
func (w *writer) colorsDict(m ast.Meta) string {
	colors := map[string]string{}
	if m.ColorScheme != "" && m.ColorScheme != "default" && m.ColorScheme != "style" {
		if p, ok := LookupPalette(m.ColorScheme); ok {
			for k, v := range p.Colors {
				colors[k] = v
			}
		} else {
			w.warn("unknown colour scheme %q (see --list-colors)", m.ColorScheme)
		}
	}
	for k, v := range m.Colors {
		k = strings.ToLower(strings.TrimSpace(k))
		switch k {
		case "background", "paper":
			k = "page"
		case "text", "body":
			k = "ink"
		case "primary":
			k = "accent"
		case "headings", "title":
			k = "heading"
		case "code", "code-background":
			k = "code-bg"
		case "table-header", "header":
			k = "table-head"
		}
		colors[k] = v
	}
	if m.Accent != "" {
		colors["accent"] = m.Accent
	}
	d := &dict{}
	keys := make([]string, 0, len(colors))
	for k := range colors {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		known := false
		for _, ck := range ColorKeys {
			if ck == k {
				known = true
			}
		}
		if !known {
			w.warn("unknown colour role %q (use one of %s)", k, strings.Join(ColorKeys, ", "))
			continue
		}
		if v := colorValue(colors[k], w); v != "none" {
			d.add(k, v)
		}
	}
	return d.String()
}

func pageOfClosure(format string) string {
	parts := strings.SplitN(format, "%d", 3)
	var sb strings.Builder
	sb.WriteString("(n, t) => [")
	vars := []string{"n", "t"}
	for i, p := range parts {
		sb.WriteString(escapeMarkup(p, i == 0))
		if i < len(parts)-1 && i < 2 {
			sb.WriteString("#" + vars[i] + ";")
		}
	}
	sb.WriteString("]")
	return sb.String()
}

// ---------------------------------------------------------------------------
// Typst value builders
// ---------------------------------------------------------------------------

type dict struct{ parts []string }

func (d *dict) add(k, v string) {
	if !strings.HasPrefix(k, "\"") {
		k = strings.TrimSpace(k)
	}
	d.parts = append(d.parts, k+": "+v)
}

func (d *dict) String() string {
	if len(d.parts) == 0 {
		return "(:)"
	}
	return "(\n  " + strings.Join(d.parts, ",\n  ") + ",\n)"
}

func array(items []string) string {
	switch len(items) {
	case 0:
		return "()"
	case 1:
		return "(" + items[0] + ",)"
	}
	return "(" + strings.Join(items, ", ") + ")"
}
