package tex2typ

// corpus is a collection of real-world formulas (textbooks, encyclopedias,
// Q&A sites, converter output) plus malformed input. Every entry must
// convert to Typst that compiles without errors or warnings.
var corpus = []string{
	// Algebra and elementary functions.
	`x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`,
	`ax^2 + bx + c = 0`,
	`(a+b)^2 = a^2 + 2ab + b^2`,
	`(a+b)^n = \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^k`,
	`a^2 - b^2 = (a-b)(a+b)`,
	`\frac{1}{1-x} = \sum_{n=0}^{\infty} x^n, \quad |x| < 1`,
	`\log_b(xy) = \log_b x + \log_b y`,
	`\ln e = 1`,
	`e^{\ln x} = x`,
	`\sqrt[3]{27} = 3`,
	`\sqrt[n]{x^m} = x^{m/n}`,
	`x^{-1} = \frac{1}{x}`,
	`|x - a| < \varepsilon`,
	`\lfloor x \rfloor \le x < \lfloor x \rfloor + 1`,
	`\lceil 2.5 \rceil = 3`,
	`a \equiv b \pmod{n}`,
	`a \bmod b`,
	`\gcd(a, b) \cdot \operatorname{lcm}(a, b) = |ab|`,
	`n! = \prod_{k=1}^{n} k`,
	`\binom{n}{k} = \frac{n!}{k!(n-k)!}`,
	`{n \choose k} = {n-1 \choose k-1} + {n-1 \choose k}`,
	`\dbinom{n}{2} = \tfrac{n(n-1)}{2}`,
	`3.14159 \approx \pi`,
	`1{,}5 + 2{,}25 = 3{,}75`,
	`f(x) = 3x^3 - 2x^2 + x - 7`,
	`x_{1,2} = \frac{-p}{2} \pm \sqrt{\left(\frac{p}{2}\right)^2 - q}`,
	`\sin^2\theta + \cos^2\theta = 1`,
	`\tan\theta = \frac{\sin\theta}{\cos\theta}`,
	`\sin(\alpha \pm \beta) = \sin\alpha\cos\beta \pm \cos\alpha\sin\beta`,
	`\cos 2\theta = \cos^2\theta - \sin^2\theta`,
	`\arctan x + \arctan\frac{1}{x} = \frac{\pi}{2}`,
	`\sinh x = \frac{e^x - e^{-x}}{2}`,
	`\cosh^2 x - \sinh^2 x = 1`,
	`\sec^2 x = 1 + \tan^2 x`,
	`\csc x \cot x`,
	`\log_{10} 1000 = 3`,
	`\lg 100 = 2`,
	`\exp(x) = \lim_{n\to\infty}\left(1 + \frac{x}{n}\right)^n`,
	`y = mx + b`,
	`\frac{a}{b} \div \frac{c}{d} = \frac{ad}{bc}`,
	`\frac{\frac{1}{x}+\frac{1}{y}}{\frac{1}{x}-\frac{1}{y}}`,
	`\cfrac{1}{1+\cfrac{1}{1+\cfrac{1}{1+x}}}`,
	`\sqrt{1+\sqrt{1+\sqrt{1+\cdots}}}`,
	`\phi = \frac{1+\sqrt{5}}{2}`,
	`x^{2^{n}}`,
	`2^{2^{2^2}} = 65536`,
	`10^{-3}\,\mathrm{m}`,
	`6.022\times10^{23}\,\mathrm{mol}^{-1}`,
	`\frac{dy}{dx} = 2x`,
	`|a+b| \leq |a| + |b|`,

	// Euler, complex numbers.
	`e^{i\pi} + 1 = 0`,
	`e^{i\theta} = \cos\theta + i\sin\theta`,
	`z = re^{i\varphi} = r(\cos\varphi + i \sin\varphi)`,
	`\overline{z_1 z_2} = \bar{z}_1 \bar{z}_2`,
	`|z|^2 = z\bar z`,
	`\Re(z) = \frac{z + \bar{z}}{2}, \quad \Im(z) = \frac{z - \bar{z}}{2i}`,
	`\arg z \in (-\pi, \pi]`,
	`(\cos x + i\sin x)^n = \cos nx + i \sin nx`,
	`\mathbb{C} \cong \mathbb{R}^2`,
	`\omega = e^{2\pi i/n}`,

	// Calculus.
	`\int_{-\infty}^{\infty} e^{-x^2}\,dx = \sqrt{\pi}`,
	`\int_0^1 x^n \, dx = \frac{1}{n+1}`,
	`\int_a^b f(x)\,\mathrm{d}x = F(b) - F(a)`,
	`\frac{d}{dx}\int_a^x f(t)\,dt = f(x)`,
	`f'(x) = \lim_{h \to 0} \frac{f(x+h)-f(x)}{h}`,
	`f''(x) + f'(x) = 0`,
	`f^{\prime}(x)`,
	`y^{(n)} = \frac{d^n y}{dx^n}`,
	`\lim_{x \to 0} \frac{\sin x}{x} = 1`,
	`\lim_{n\rightarrow\infty} \left(1+\frac{1}{n}\right)^n = e`,
	`\lim\limits_{x\to a^+} f(x)`,
	`\limsup_{n\to\infty} a_n`,
	`\liminf_{n\to\infty} a_n \le \limsup_{n\to\infty} a_n`,
	`\sum_{n=1}^{\infty} \frac{1}{n^2} = \frac{\pi^2}{6}`,
	`\sum_{i=1}^n i = \frac{n(n+1)}{2}`,
	`\sum\limits_{k=1}^{n} k^2`,
	`\sum\nolimits_{k} a_k`,
	`\prod_{p \text{ prime}} \frac{1}{1-p^{-s}} = \zeta(s)`,
	`f(x) = \sum_{n=0}^\infty \frac{f^{(n)}(a)}{n!}(x-a)^n`,
	`e^x = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \cdots`,
	`\ln(1+x) = x - \frac{x^2}{2} + \frac{x^3}{3} - \dots`,
	`\frac{\partial f}{\partial x}`,
	`\frac{\partial^2 u}{\partial t^2} = c^2 \nabla^2 u`,
	`\frac{\partial^2 f}{\partial x \partial y}`,
	`\nabla f = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z} \right)`,
	`\nabla \cdot \mathbf{F} = \frac{\partial F_x}{\partial x} + \frac{\partial F_y}{\partial y} + \frac{\partial F_z}{\partial z}`,
	`\nabla \times \mathbf{F}`,
	`\Delta u = \nabla^2 u = 0`,
	`\iint_D f(x,y)\,dA`,
	`\iiint_V \rho\, dV`,
	`\oint_C \mathbf{F} \cdot d\mathbf{r} = \iint_S (\nabla \times \mathbf{F}) \cdot d\mathbf{S}`,
	`\int\limits_0^1 f`,
	`\int\!\!\int f\,dx\,dy`,
	`\int_0^{2\pi} \int_0^\pi \sin\theta \, d\theta \, d\phi = 4\pi`,
	`\frac{\mathrm{d}}{\mathrm{d}t} \left( \frac{\partial L}{\partial \dot{q}} \right) - \frac{\partial L}{\partial q} = 0`,
	`\dot{x} = v, \quad \ddot{x} = a`,
	`\dddot{x}`,
	`\Gamma(z) = \int_0^\infty t^{z-1} e^{-t}\, dt`,
	`\Gamma(n) = (n-1)!`,
	`B(x,y) = \frac{\Gamma(x)\Gamma(y)}{\Gamma(x+y)}`,
	`\zeta(s) = \sum_{n=1}^\infty n^{-s}`,
	`\int u\,dv = uv - \int v\,du`,
	`\left.\frac{df}{dx}\right|_{x=0}`,
	`\left. F(x) \right|_a^b`,
	`\mathcal{L}\{f(t)\} = \int_0^\infty f(t) e^{-st}\,dt`,
	`\hat{f}(\xi) = \int_{-\infty}^{\infty} f(x)\, e^{-2\pi i x \xi}\,dx`,
	`f(x) = \int_{-\infty}^{\infty} \hat f(\xi)\,e^{2 \pi i \xi x} \,d\xi`,
	`\mathcal{F}\{f * g\} = \mathcal{F}\{f\} \cdot \mathcal{F}\{g\}`,
	`(f * g)(t) = \int_{-\infty}^{\infty} f(\tau) g(t - \tau)\, d\tau`,
	`a_0 + \sum_{n=1}^\infty \left( a_n \cos\frac{n\pi x}{L} + b_n \sin\frac{n\pi x}{L} \right)`,
	`\delta(x) = \frac{1}{2\pi}\int_{-\infty}^\infty e^{ikx}\,dk`,
	`\oint_{\partial \Omega} \omega = \int_\Omega d\omega`,
	`\frac{dy}{dt} = ky \implies y = Ce^{kt}`,
	`y'' + p(x) y' + q(x) y = 0`,
	`\left| \int_a^b f \right| \le \int_a^b |f|`,
	`\int_{\mathbb{R}^n} e^{-\|x\|^2} dx = \pi^{n/2}`,
	`\idotsint_V f`,
	`\sum_{\substack{0 \le i \le m \\ 0 < j < n}} P(i,j)`,
	`\sum_{\begin{subarray}{l} i \in \Lambda \\ 0<j<n \end{subarray}} P(i,j)`,

	// Physics.
	`E = mc^2`,
	`F = ma`,
	`\vec{F} = m\vec{a}`,
	`\mathbf{F} = q(\mathbf{E} + \mathbf{v} \times \mathbf{B})`,
	`\nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0}`,
	`\nabla \cdot \mathbf{B} = 0`,
	`\nabla \times \mathbf{E} = -\frac{\partial \mathbf{B}}{\partial t}`,
	`\nabla \times \mathbf{B} = \mu_0\left(\mathbf{J} + \varepsilon_0 \frac{\partial \mathbf{E}}{\partial t}\right)`,
	`\begin{aligned} \nabla \cdot \mathbf{E} &= \frac{\rho}{\varepsilon_0} \\ \nabla \cdot \mathbf{B} &= 0 \\ \nabla \times \mathbf{E} &= -\frac{\partial \mathbf{B}}{\partial t} \\ \nabla \times \mathbf{B} &= \mu_0\mathbf{J} + \mu_0\varepsilon_0\frac{\partial \mathbf{E}}{\partial t} \end{aligned}`,
	`i\hbar\frac{\partial}{\partial t}\Psi(\mathbf{r},t) = \hat{H}\Psi(\mathbf{r},t)`,
	`-\frac{\hbar^2}{2m}\nabla^2\psi + V\psi = E\psi`,
	`\hat{H} = -\frac{\hbar^2}{2m}\frac{d^2}{dx^2} + V(x)`,
	`\Delta x \, \Delta p \geq \frac{\hbar}{2}`,
	`[\hat{x}, \hat{p}] = i\hbar`,
	`\langle \psi | \phi \rangle`,
	`\langle\psi|\hat{A}|\psi\rangle`,
	`\left\langle \psi \middle| \hat{H} \middle| \psi \right\rangle`,
	`|\psi\rangle = \alpha|0\rangle + \beta|1\rangle`,
	`\rho = \sum_i p_i |\psi_i\rangle\langle\psi_i|`,
	`E = h\nu = \hbar\omega`,
	`\lambda = \frac{h}{p}`,
	`p^\mu p_\mu = m^2c^2`,
	`R_{\mu\nu} - \frac{1}{2}R g_{\mu\nu} + \Lambda g_{\mu\nu} = \frac{8\pi G}{c^4} T_{\mu\nu}`,
	`ds^2 = -c^2dt^2 + dx^2 + dy^2 + dz^2`,
	`g_{\mu\nu} = \eta_{\mu\nu} + h_{\mu\nu}`,
	`\Gamma^\lambda_{\mu\nu} = \frac{1}{2} g^{\lambda\sigma}(\partial_\mu g_{\nu\sigma} + \partial_\nu g_{\mu\sigma} - \partial_\sigma g_{\mu\nu})`,
	`R^\rho{}_{\sigma\mu\nu} = \partial_\mu\Gamma^\rho_{\nu\sigma} - \partial_\nu\Gamma^\rho_{\mu\sigma}`,
	`T^{\mu\nu}{}_{;\nu} = 0`,
	`F_{\mu\nu} = \partial_\mu A_\nu - \partial_\nu A_\mu`,
	`\mathcal{L} = -\frac{1}{4}F_{\mu\nu}F^{\mu\nu} + \bar\psi(i\gamma^\mu D_\mu - m)\psi`,
	`\gamma = \frac{1}{\sqrt{1 - v^2/c^2}}`,
	`t' = \gamma\left(t - \frac{vx}{c^2}\right)`,
	`PV = nRT`,
	`S = k_B \ln \Omega`,
	`\Delta G = \Delta H - T\Delta S`,
	`dU = \delta Q - \delta W`,
	`\oint \frac{\delta Q}{T} \le 0`,
	`Z = \sum_i e^{-\beta E_i}`,
	`\langle E \rangle = -\frac{\partial \ln Z}{\partial \beta}`,
	`F = G\frac{m_1 m_2}{r^2}`,
	`\vec{\tau} = \vec{r} \times \vec{F}`,
	`L = \frac{1}{2}mv^2 - V(q)`,
	`\frac{\partial H}{\partial p} = \dot q,\quad \frac{\partial H}{\partial q} = -\dot p`,
	`\omega = 2\pi f`,
	`v = \lambda f`,
	`I = I_0 e^{-\mu x}`,
	`V = IR`,
	`P = \frac{V^2}{R}`,
	`\mathbf{p} = \gamma m \mathbf{v}`,
	`\overrightarrow{AB} + \overrightarrow{BC} = \overrightarrow{AC}`,
	`\vec{a} \cdot \vec{b} = |\vec{a}||\vec{b}|\cos\theta`,
	`\hat{\mathbf{n}} = \frac{\mathbf{n}}{\|\mathbf{n}\|}`,
	`\boldsymbol{\sigma} \cdot \hat{\boldsymbol{n}}`,
	`\bm{x}^\top \bm{A} \bm{x}`,
	`\psi(x,t) = A e^{i(kx - \omega t)}`,
	`a^\dagger|n\rangle = \sqrt{n+1}|n+1\rangle`,
	`[a, a^\dagger] = 1`,
	`\{A, B\} = AB + BA`,
	`\sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}`,
	`\epsilon_{ijk}\epsilon_{imn} = \delta_{jm}\delta_{kn} - \delta_{jn}\delta_{km}`,
	`\delta_{ij} = \begin{cases} 1 & i = j \\ 0 & i \neq j \end{cases}`,
	`T^{i_1 \dots i_p}_{j_1 \dots j_q}`,
	`\nabla_\mu T^{\mu\nu} = 0`,
	`\square \phi = 0`,
	`\Box\phi + m^2\phi = 0`,
	`\hbar = \frac{h}{2\pi}`,
	`k_{\mathrm{B}} T`,
	`\mu_0 = 4\pi \times 10^{-7}\,\mathrm{H/m}`,
	`c = 299\,792\,458\ \mathrm{m/s}`,
	`25^\circ\mathrm{C}`,
	`\theta = 45^{\circ}`,
	`\angle ABC = 90^\circ`,
	`\SI`,

	// Chemistry-like.
	`\mathrm{H_2O}`,
	`\mathrm{CO_2} + \mathrm{H_2O} \rightleftharpoons \mathrm{H_2CO_3}`,
	`2\mathrm{H}_2 + \mathrm{O}_2 \rightarrow 2\mathrm{H}_2\mathrm{O}`,
	`\mathrm{Fe^{3+}} + 3\,\mathrm{OH^-} \longrightarrow \mathrm{Fe(OH)_3}\downarrow`,
	`{}^{14}_{6}\mathrm{C}`,
	`{}^{235}\mathrm{U}`,
	`\mathrm{CH_3COOH} \rightleftharpoons \mathrm{CH_3COO^-} + \mathrm{H^+}`,
	`K_a = \frac{[\mathrm{H^+}][\mathrm{A^-}]}{[\mathrm{HA}]}`,
	`\mathrm{pH} = -\log_{10}[\mathrm{H^+}]`,
	`\Delta_r H^\circ = \sum \nu \Delta_f H^\circ`,
	`\mathrm{N_2 + 3H_2 \xrightarrow{Fe} 2NH_3}`,
	`A \xrightarrow[\text{heat}]{\text{catalyst}} B`,
	`A \xleftarrow{k_{-1}} B`,
	`\mathrm{Na^+ + Cl^- \to NaCl}`,
	`\ce`,

	// Linear algebra.
	`\begin{pmatrix} a & b \\ c & d \end{pmatrix}`,
	`\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}`,
	`\det\begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc`,
	`\begin{vmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{vmatrix}`,
	`\begin{Vmatrix} x \end{Vmatrix}`,
	`\begin{Bmatrix} 1 & 2 \\ 3 & 4 \end{Bmatrix}`,
	`\begin{matrix} a & b \\ c & d \end{matrix}`,
	`\left( \begin{matrix} a & b \\ c & d \end{matrix} \right)`,
	`\left[ \begin{array}{cc|c} 1 & 2 & 3 \\ 4 & 5 & 6 \end{array} \right]`,
	`\begin{array}{|c|c|} \hline a & b \\ \hline c & d \\ \hline \end{array}`,
	`\begin{array}{lcr} \text{left} & \text{center} & \text{right} \\ x & y & z \end{array}`,
	`\begin{array}{rl} x &= 1 \\ yy &= 22 \end{array}`,
	`A = \begin{pmatrix} a_{11} & \cdots & a_{1n} \\ \vdots & \ddots & \vdots \\ a_{m1} & \cdots & a_{mn} \end{pmatrix}`,
	`\begin{pmatrix} 1 & & \\ & \ddots & \\ & & 1 \end{pmatrix}`,
	`A^{-1} = \frac{1}{\det A}\operatorname{adj}A`,
	`A\mathbf{x} = \mathbf{b}`,
	`A = U\Sigma V^T`,
	`A = Q\Lambda Q^{-1}`,
	`\det(A - \lambda I) = 0`,
	`\operatorname{tr}(AB) = \operatorname{tr}(BA)`,
	`\mathrm{rank}(A) + \dim\ker A = n`,
	`\langle u, v \rangle = \sum_i u_i \overline{v_i}`,
	`\|x\|_2 = \sqrt{\sum_{i=1}^n x_i^2}`,
	`\lVert x \rVert_\infty = \max_i |x_i|`,
	`\left\| A \right\|_F`,
	`\mathbf{u} \otimes \mathbf{v}`,
	`V = U \oplus W`,
	`\begin{smallmatrix} a & b \\ c & d \end{smallmatrix}`,
	`\bigl(\begin{smallmatrix} a & b \\ c & d \end{smallmatrix}\bigr)`,
	`\begin{pmatrix*}[r] -1 & 3 \\ 2 & -4 \end{pmatrix*}`,
	`x^T A x > 0 \quad \forall x \neq 0`,
	`\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}`,
	`\begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix}`,
	`J = \begin{bmatrix} \dfrac{\partial f_1}{\partial x_1} & \cdots & \dfrac{\partial f_1}{\partial x_n} \\ \vdots & \ddots & \vdots \\ \dfrac{\partial f_m}{\partial x_1} & \cdots & \dfrac{\partial f_m}{\partial x_n} \end{bmatrix}`,
	`\operatorname{span}\{v_1, \ldots, v_k\}`,
	`\mathrm{GL}_n(\mathbb{R})`,
	`\mathfrak{su}(2) \cong \mathfrak{so}(3)`,
	`AB \neq BA`,
	`\begin{array}{c|ccc} + & 0 & 1 & 2 \\ \hline 0 & 0 & 1 & 2 \\ 1 & 1 & 2 & 0 \end{array}`,
	`\left(\begin{array}{@{}c@{}} x \\ y \end{array}\right)`,
	`\begin{array}{*{3}{c}} 1 & 2 & 3 \end{array}`,

	// Piecewise and cases.
	`f(x) = \begin{cases} x^2 & \text{if } x \ge 0 \\ -x & \text{otherwise} \end{cases}`,
	`|x| = \begin{cases} x, & x \geq 0 \\ -x, & x < 0 \end{cases}`,
	`\operatorname{sgn}(x) = \begin{cases} -1 & x < 0 \\ 0 & x = 0 \\ 1 & x > 0 \end{cases}`,
	`f(n) = \begin{cases} n/2 & \text{if } n \equiv 0 \pmod 2 \\ 3n+1 & \text{if } n \equiv 1 \pmod 2 \end{cases}`,
	`H(x) = \begin{dcases} 0, & x < 0 \\ \frac{1}{2}, & x = 0 \\ 1, & x > 0 \end{dcases}`,
	`\begin{rcases} a &\text{if } b \\ c &\text{if } d \end{rcases} \implies e`,
	`f(x) = \left\{ \begin{array}{ll} 0 & x < 0 \\ 1 & x \ge 0 \end{array} \right.`,
	`\left\{ \begin{aligned} x + y &= 3 \\ x - y &= 1 \end{aligned} \right.`,
	`\begin{cases} \dot x = y \\ \dot y = -x \end{cases}`,
	`\chi_A(x) = \begin{cases}1 & \text{if } x \in A,\\0 & \text{if } x \notin A.\end{cases}`,

	// Aligned derivations.
	`\begin{align} a &= b + c \\ &= d \label{eq:x} \end{align}`,
	`\begin{align*} f(x) &= (x+1)^2 \\ &= x^2 + 2x + 1 \end{align*}`,
	`\begin{aligned} (a+b)^2 &= (a+b)(a+b) \\ &= a^2 + ab + ba + b^2 \\ &= a^2 + 2ab + b^2 \end{aligned}`,
	`\begin{align} x &= 1 & y &= 2 \\ z &= 3 & w &= 4 \end{align}`,
	`\begin{alignat}{2} x &= y + z &\quad& \text{(1)} \\ a &= b && \text{(2)} \end{alignat}`,
	`\begin{gather} a = b \\ c = d \end{gather}`,
	`\begin{gather*} x + y = z \\ \int f = F \end{gather*}`,
	`\begin{multline} a + b + c + d + e \\ + f + g + h \end{multline}`,
	`\begin{split} a &= b \\ &= c \end{split}`,
	`\begin{equation} \begin{split} H &= \sum_i p_i \\ &\quad + V \end{split} \end{equation}`,
	`\begin{equation} E = mc^2 \label{eq:einstein} \end{equation}`,
	`\begin{equation*} a = b \end{equation*}`,
	`\begin{eqnarray} a &=& b \\ c &=& d \nonumber \end{eqnarray}`,
	`\begin{eqnarray*} x &\le& y \end{eqnarray*}`,
	`\begin{flalign} a &= b & c &= d \end{flalign}`,
	`x = \begin{aligned}[t] a &= b \\ &= c \end{aligned}`,
	`\begin{gathered} a \\ b + c \end{gathered}`,
	`\begin{align} a &= b \nonumber \\ c &= d \notag \end{align}`,
	`\begin{align} a &= b \tag{1.1} \end{align}`,
	`\begin{align} \int_0^1 f &= \sum_{k=1}^n \frac{1}{k} \\ &\le \log n + 1 \end{align}`,
	`a = b \\ c = d`,
	`a &= b \\ &= c`,
	`\begin{align} a &= b \\ \intertext{and} c &= d \end{align}`,
	`\left\{\begin{array}{rl} x &\mapsto x^2 \\ y &\mapsto y^3 \end{array}\right.`,

	// Sets and logic.
	`\{ x \in \mathbb{R} \mid x > 0 \}`,
	`\{x : x^2 < 2\}`,
	`\left\{ \frac{1}{n} : n \in \mathbb{N} \right\}`,
	`A \cup B = \{x \mid x \in A \lor x \in B\}`,
	`A \cap B \subseteq A`,
	`A \setminus B`,
	`\overline{A \cup B} = \bar A \cap \bar B`,
	`A^c = U \setminus A`,
	`\emptyset \subset A`,
	`\varnothing`,
	`\mathcal{P}(A) = \{ B : B \subseteq A \}`,
	`|A \times B| = |A| \cdot |B|`,
	`\bigcup_{i=1}^n A_i`,
	`\bigcap_{i \in I} A_i`,
	`\forall \varepsilon > 0\ \exists \delta > 0 : |x - a| < \delta \Rightarrow |f(x) - f(a)| < \varepsilon`,
	`\neg(p \land q) \iff \neg p \lor \neg q`,
	`p \to q \equiv \lnot p \vee q`,
	`\vdash \phi \implies \models \phi`,
	`\Gamma \vdash A \to B`,
	`\exists! x\, P(x)`,
	`\nexists x \in \emptyset`,
	`x \notin A`,
	`A \not\subset B`,
	`a \not= b`,
	`a \not\equiv b`,
	`\aleph_0 < 2^{\aleph_0}`,
	`\mathbb{N} \subsetneq \mathbb{Z} \subsetneq \mathbb{Q} \subsetneq \mathbb{R} \subsetneq \mathbb{C}`,
	`\top \land \bot = \bot`,
	`f \colon A \to B`,
	`f: X \rightarrow Y`,
	`x \mapsto x^2`,
	`g \circ f`,
	`A \twoheadrightarrow B \hookrightarrow C`,
	`\mathbb{Z}/n\mathbb{Z}`,
	`\ker\varphi \trianglelefteq G`,
	`G/N \cong H`,
	`H \le G`,
	`[G : H] = \frac{|G|}{|H|}`,
	`\langle a, b \mid a^2 = b^3 = 1 \rangle`,
	`\operatorname{Hom}(V, W)`,
	`\hom(A, B)`,
	`A \times B \to C`,
	`\varprojlim A_n`,
	`\varinjlim A_n`,

	// Probability and statistics.
	`P(A|B) = \frac{P(B|A)P(A)}{P(B)}`,
	`P(A \mid B) = \frac{P(A \cap B)}{P(B)}`,
	`\Pr[X \ge a] \le \frac{\mathbb{E}[X]}{a}`,
	`\mathbb{E}[X] = \sum_x x\,p(x)`,
	`\operatorname{Var}(X) = \mathbb{E}[X^2] - (\mathbb{E}[X])^2`,
	`\sigma^2 = \frac{1}{N}\sum_{i=1}^N (x_i - \mu)^2`,
	`s = \sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}`,
	`\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i`,
	`f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2}`,
	`X \sim \mathcal{N}(\mu, \sigma^2)`,
	`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}`,
	`P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}`,
	`\operatorname{Cov}(X, Y) = \mathbb{E}[(X - \mu_X)(Y - \mu_Y)]`,
	`\rho_{X,Y} = \frac{\operatorname{cov}(X,Y)}{\sigma_X \sigma_Y}`,
	`z = \frac{\bar{x} - \mu}{\sigma/\sqrt{n}}`,
	`\chi^2 = \sum \frac{(O_i - E_i)^2}{E_i}`,
	`\hat{\beta} = (X^T X)^{-1} X^T y`,
	`\hat\theta_{\mathrm{MLE}} = \arg\max_\theta \mathcal{L}(\theta)`,
	`\operatorname*{arg\,max}_{\theta} p(x \mid \theta)`,
	`\operatorname*{argmin}_{w} \|Xw - y\|^2 + \lambda\|w\|_1`,
	`H(X) = -\sum_{x} p(x) \log_2 p(x)`,
	`D_{\mathrm{KL}}(P \parallel Q) = \sum_x P(x) \log \frac{P(x)}{Q(x)}`,
	`I(X;Y) = H(X) - H(X \mid Y)`,
	`\Phi(z) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^z e^{-t^2/2}\,dt`,
	`P\left(\bigcup_{i} A_i\right) \le \sum_i P(A_i)`,
	`\lim_{n \to \infty} P\left( \left| \bar X_n - \mu \right| > \varepsilon \right) = 0`,
	`\sqrt{n}(\bar X_n - \mu) \xrightarrow{d} \mathcal{N}(0, \sigma^2)`,
	`X_n \xrightarrow{\text{a.s.}} X`,
	`p(\theta \mid x) \propto p(x \mid \theta)\, p(\theta)`,
	`\mathbb{1}_{\{X > 0\}}`,
	`F_X(x) = \Pr(X \le x)`,
	`\mathrm{E}\left[ e^{tX} \right]`,
	`R^2 = 1 - \frac{SS_{\text{res}}}{SS_{\text{tot}}}`,

	// Number theory and combinatorics.
	`a^{p-1} \equiv 1 \pmod{p}`,
	`\varphi(n) = n \prod_{p \mid n} \left(1 - \frac{1}{p}\right)`,
	`\sum_{d \mid n} \varphi(d) = n`,
	`\pi(x) \sim \frac{x}{\ln x}`,
	`F_n = F_{n-1} + F_{n-2}`,
	`F_n = \frac{\phi^n - (-\phi)^{-n}}{\sqrt 5}`,
	`\left\lfloor \frac{n}{2} \right\rfloor`,
	`\left\lceil \log_2 n \right\rceil`,
	`n \choose k`,
	`\genfrac{(}{)}{0pt}{}{n}{k}`,
	`\genfrac{}{}{}{0}{a}{b}`,
	`\sum_{k=0}^n \binom{n}{k} = 2^n`,
	`C_n = \frac{1}{n+1}\binom{2n}{n}`,
	`S(n,k) = \frac{1}{k!}\sum_{j=0}^{k}(-1)^{k-j}\binom{k}{j}j^n`,
	`p \nmid a`,
	`3 \mid 12`,
	`\mathbb{Z}_p^\times`,
	`x \equiv a_i \pmod{m_i}`,
	`\left(\frac{a}{p}\right) \equiv a^{\frac{p-1}{2}} \pmod p`,
	`\gcd(a,b) = 1`,
	`\mod`,

	// Analysis and topology.
	`\|f\|_{L^p} = \left(\int |f|^p \, d\mu\right)^{1/p}`,
	`\sup_{x \in X} |f(x)|`,
	`\inf_{n} a_n`,
	`\max\{a, b\}`,
	`\min_{x \in [0,1]} f(x)`,
	`f \in C^\infty(\mathbb{R})`,
	`L^2(\Omega)`,
	`\overline{B(x, r)}`,
	`\partial\Omega`,
	`\mathring{A}`,
	`d(x, y) \le d(x, z) + d(z, y)`,
	`\lim_{n\to\infty} \|f_n - f\|_\infty = 0`,
	`f_n \rightrightarrows f`,
	`f(x) = O(g(x))`,
	`f(n) = \Theta(n \log n)`,
	`f = o(g) \text{ as } x \to 0`,
	`\sum_{n=1}^\infty \frac{(-1)^{n+1}}{n} = \ln 2`,
	`\prod_{n=1}^{\infty} \left(1 - \frac{x^2}{n^2\pi^2}\right) = \frac{\sin x}{x}`,
	`\int_\gamma f(z)\, dz = 2\pi i \sum \operatorname{Res}(f, a_k)`,
	`\oint_{|z|=1} \frac{dz}{z} = 2\pi i`,
	`\frac{\partial u}{\partial x} = \frac{\partial v}{\partial y}, \quad \frac{\partial u}{\partial y} = -\frac{\partial v}{\partial x}`,
	`\epsilon\text{-}\delta`,
	`\bigoplus_{i \in I} V_i`,
	`\bigotimes_{k=1}^n V`,
	`\coprod_{i} X_i`,
	`\bigvee_{i} p_i \quad \bigwedge_{j} q_j`,
	`\biguplus_k A_k`,
	`\bigsqcup_n U_n`,
	`\bigodot_i x_i`,

	// Computer science.
	`O(n \log n)`,
	`T(n) = 2T\left(\frac{n}{2}\right) + O(n)`,
	`\Omega(n^2)`,
	`\mathcal{O}(1)`,
	`\lceil \log_2(n+1) \rceil`,
	`\text{if } x > 0 \text{ then } y \gets x`,
	`x \leftarrow x + 1`,
	`A \Rightarrow B \Leftarrow C \Leftrightarrow D`,
	`\sigma(z) = \frac{1}{1 + e^{-z}}`,
	`\mathrm{softmax}(z)_i = \frac{e^{z_i}}{\sum_j e^{z_j}}`,
	`\operatorname{ReLU}(x) = \max(0, x)`,
	`\nabla_\theta J(\theta) = \mathbb{E}_{\pi_\theta}\left[ \nabla_\theta \log \pi_\theta(a|s) Q^{\pi}(s,a) \right]`,
	`\mathcal{L}(\theta) = -\frac{1}{N}\sum_{i=1}^N \left[ y_i \log \hat y_i + (1-y_i)\log(1 - \hat y_i) \right]`,
	`\theta_{t+1} = \theta_t - \eta \nabla_\theta \mathcal{L}(\theta_t)`,
	`\mathrm{Attention}(Q,K,V) = \mathrm{softmax}\left(\frac{QK^\top}{\sqrt{d_k}}\right)V`,
	`h_t = \tanh(W_{hh} h_{t-1} + W_{xh} x_t)`,
	`\{0, 1\}^*`,
	`L = \{ a^n b^n \mid n \ge 0 \}`,
	`\delta : Q \times \Sigma \to Q`,
	`\mathsf{P} \stackrel{?}{=} \mathsf{NP}`,
	`\mathtt{x} := \mathtt{x} + 1`,
	`x := y`,
	`a \coloneqq b`,
	`\lambda x.\, x + 1`,
	`(\lambda x. M) N \to_\beta M[x := N]`,
	`\Gamma \vdash e : \tau`,
	`\frac{\Gamma \vdash e_1 : \tau_1 \to \tau_2 \quad \Gamma \vdash e_2 : \tau_1}{\Gamma \vdash e_1\, e_2 : \tau_2}`,
	`\llbracket e \rrbracket_\rho`,
	`a \oplus b`,
	`\overline{A + B} = \bar{A} \cdot \bar{B}`,
	`\mathbf{x} \in \{0,1\}^n`,
	`\#\{x : f(x) = 1\}`,
	`50\%`,
	`\$100`,
	`a \& b`,
	`\_`,
	`x_\text{max}`,
	`v_{\text{max}} = 3\,\mathrm{m/s}`,
	`\text{Speed} = \frac{\text{Distance}}{\text{Time}}`,
	`\text{the "quoted" text}`,
	`\textbf{bold} \textit{italic} \texttt{mono} \textsf{sans}`,
	`\mbox{if } x \in A`,
	`\text{area} = \pi r^2 \text{ where } r = \text{radius}`,
	`\text{for all } n \ge 1`,
	`\text{Let $x$ be real}`,
	`\text{50\% of } x`,
	`\text{na\"ive caf\'e}`,
	`\text{x -- y --- z}`,
	"\\text{``quoted''}",

	// Geometry and trigonometry.
	`a^2 + b^2 = c^2`,
	`c^2 = a^2 + b^2 - 2ab\cos\gamma`,
	`\frac{a}{\sin\alpha} = \frac{b}{\sin\beta} = \frac{c}{\sin\gamma}`,
	`A = \pi r^2`,
	`V = \frac{4}{3}\pi r^3`,
	`\triangle ABC \sim \triangle DEF`,
	`\angle A + \angle B + \angle C = 180^\circ`,
	`\overline{AB} \parallel \overline{CD}`,
	`AB \perp CD`,
	`\measuredangle ABC`,
	`\widehat{ABC}`,
	`\overset{\frown}{AB}`,
	`\vec{v} = \langle v_1, v_2, v_3 \rangle`,
	`\|\vec{v}\| = \sqrt{v_1^2 + v_2^2 + v_3^2}`,
	`x^2 + y^2 = r^2`,
	`\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1`,
	`K = \frac{1}{R_1 R_2}`,
	`\kappa = \frac{|x'y'' - y'x''|}{(x'^2 + y'^2)^{3/2}}`,
	`\int_C f\,ds = \int_a^b f(\mathbf{r}(t)) \|\mathbf{r}'(t)\|\,dt`,

	// Accents, fonts and decorations.
	`\hat{x}\ \check{x}\ \tilde{x}\ \acute{x}\ \grave{x}\ \dot{x}\ \ddot{x}\ \breve{x}\ \bar{x}\ \vec{x}`,
	`\widetilde{abc} \quad \widehat{xyz}`,
	`\overline{abc} \quad \underline{xyz}`,
	`\overleftarrow{AB} \quad \overleftrightarrow{AB}`,
	`\underbrace{a + b + \cdots + z}_{26}`,
	`\overbrace{1 + 2 + \cdots + n}^{\text{n terms}}`,
	`\underbrace{\overbrace{a+b}^{x}+c}_{y}`,
	`\mathrm{abc}\ \mathit{abc}\ \mathbf{abc}\ \mathsf{abc}\ \mathtt{abc}`,
	`\mathcal{A}\ \mathscr{B}\ \mathfrak{C}\ \mathbb{D}`,
	`\mathbb{1}`,
	`\mathbf{0} \ne \mathbf{1}`,
	`\boldsymbol{\alpha} + \boldsymbol{\beta}`,
	`\pmb{x}`,
	`{\rm d}x`,
	`{\bf v} \cdot {\bf w}`,
	`{\it et\ al.}`,
	`{\cal L}`,
	`\mathrm{e}^{\mathrm{i}\pi}`,
	`\mathit{diff}`,
	`\mathbf{\nabla}`,
	`\boxed{E = mc^2}`,
	`\boxed{x = \frac{-b \pm \sqrt{b^2-4ac}}{2a}}`,
	`\fbox{text}`,
	`\phantom{x} + y`,
	`x \hphantom{=} y`,
	`\left( \vphantom{\int} x \right)`,
	`\cancel{x} + \bcancel{y} + \xcancel{z}`,
	`\frac{\cancel{2}x}{\cancel{2}}`,
	`\color{red} x + y`,
	`{\color{blue} a} + b`,
	`\textcolor{green}{x^2}`,
	`\textcolor[HTML]{FF8800}{y}`,
	`\color{red!50!blue}{z}`,
	`\colorbox{yellow}{important}`,
	`\displaystyle\sum_{i=1}^n i`,
	`\textstyle\sum_{i=1}^n i`,
	`\scriptstyle a + b`,
	`a {\displaystyle \frac{1}{2}} b`,
	`x \mathrel{R} y`,
	`a \mathbin{\#} b`,
	`\mathop{\mathrm{sgn}} x`,
	`\mathop{\sum}\limits_{i} x_i`,
	`\mathord{+}`,
	`\mathopen{[} 0, 1 \mathclose{]}`,

	// Delimiters.
	`\left( \frac{a}{b} \right)^2`,
	`\left[ \frac{a}{b} \right]`,
	`\left\{ \frac{a}{b} \right\}`,
	`\left| \frac{a}{b} \right|`,
	`\left\| \frac{a}{b} \right\|`,
	`\left\langle \frac{a}{b} \right\rangle`,
	`\left\lfloor \frac{a}{b} \right\rfloor`,
	`\left\lceil \frac{a}{b} \right\rceil`,
	`\left. \frac{a}{b} \right|`,
	`\left( \frac{a}{b} \right.`,
	`\left[ 0, 1 \right)`,
	`\left( 0, 1 \right]`,
	`\left< x \right>`,
	`\left\lvert x \right\rvert`,
	`\left\lVert x \right\rVert`,
	`\left/ \frac{a}{b} \right\backslash`,
	`\left\uparrow \frac{a}{b} \right\downarrow`,
	`\left( \left( \left( x \right) \right) \right)`,
	`\left\{ x \;\middle|\; x > 0 \right\}`,
	`\big( \Big( \bigg( \Bigg( x \Bigg) \bigg) \Big) \big)`,
	`\bigl[ x \bigr]`,
	`\Bigl\{ x \Bigm| y \Bigr\}`,
	`\biggl\langle x \biggr\rangle`,
	`\big| x \big|`,
	`\big\| x \big\|`,
	`\big.`,
	`[0, 1)`,
	`(0, 1]`,
	`]a, b[`,
	`\{1, 2, 3\}`,
	`\lbrace x \rbrace`,
	`\lbrack x \rbrack`,
	`\langle x, y \rangle`,
	`\lvert x \rvert \quad \lVert x \rVert`,
	`|x|`,
	`\|x\|`,
	`\vert x \vert`,
	`\Vert x \Vert`,
	`\llcorner x \lrcorner`,
	`\lgroup x \rgroup`,
	`\frac{[a, b)}{(c, d]}`,
	`\sqrt{(x)}`,
	`f\left(\frac{1}{2}\right)`,

	// Spacing.
	`a\,b\:c\;d\!e\ f~g\quad h\qquad i`,
	`a \thinspace b \medspace c \thickspace d \negthinspace e`,
	`a \hspace{1cm} b`,
	`a \hspace*{2em} b`,
	`a \kern 3pt b \mkern 6mu c`,
	`a \mskip 3mu b`,
	`a \enspace b`,
	`a \hspace{\fill} b`,
	`x\!\!\!y`,

	// Symbols galore.
	`\alpha\beta\gamma\delta\epsilon\varepsilon\zeta\eta\theta\vartheta\iota\kappa\varkappa\lambda\mu\nu\xi\omicron\pi\varpi\rho\varrho\sigma\varsigma\tau\upsilon\phi\varphi\chi\psi\omega`,
	`\Gamma\Delta\Theta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega`,
	`\varGamma \varDelta \varOmega`,
	`\aleph \beth \gimel \daleth`,
	`\leq \geq \neq \le \ge \ne \approx \equiv \sim \simeq \cong \propto \ll \gg`,
	`\prec \succ \preceq \succeq \parallel \perp \mid \nmid \models \vdash \dashv`,
	`\pm \mp \times \div \cdot \circ \bullet \star \ast \oplus \ominus \otimes \oslash \odot`,
	`\wedge \vee \cap \cup \setminus \sqcup \uplus \amalg \dagger \ddagger`,
	`\in \notin \ni \subset \subseteq \supset \supseteq \subsetneq \emptyset \varnothing`,
	`\forall \exists \nexists \neg \lnot \land \lor \top \bot`,
	`\to \gets \rightarrow \leftarrow \leftrightarrow \Rightarrow \Leftarrow \Leftrightarrow`,
	`\implies \impliedby \iff \mapsto \longmapsto \longrightarrow \longleftarrow`,
	`\uparrow \downarrow \updownarrow \Uparrow \Downarrow \nearrow \searrow \swarrow \nwarrow`,
	`\hookrightarrow \hookleftarrow \rightharpoonup \leftrightharpoons \rightleftharpoons`,
	`\infty \partial \nabla \hbar \ell \Re \Im \aleph \beth \wp \angle \measuredangle`,
	`\triangle \square \Box \diamond \clubsuit \diamondsuit \heartsuit \spadesuit`,
	`\prime \degree \checkmark \therefore \because \ldots \cdots \vdots \ddots \dots`,
	`\langle \rangle \lfloor \rfloor \lceil \rceil \lvert \rvert \lVert \rVert \| \{ \} \backslash`,
	`\sum \prod \coprod \int \iint \iiint \oint \bigcup \bigcap \bigoplus \bigotimes \bigvee \bigwedge \biguplus`,
	`\sin \cos \tan \cot \sec \csc \arcsin \arccos \arctan \sinh \cosh \tanh \coth`,
	`\log \ln \lg \exp \det \dim \ker \hom \arg \deg \gcd \lim \liminf \limsup \max \min \sup \inf \Pr`,
	`\lesssim \gtrsim \lessgtr \leqslant \geqslant \nleq \ngeq \lneq \gneqq`,
	`\vartriangleleft \trianglerighteq \ntriangleleft \lhd \unrhd`,
	`\sqsubseteq \sqsupset \Subset \Supset \subseteqq \supsetneqq`,
	`\boxplus \boxminus \boxtimes \boxdot \circledast \circledcirc \circleddash`,
	`\ltimes \rtimes \leftthreetimes \rightthreetimes \divideontimes \dotplus`,
	`\curvearrowleft \curvearrowright \circlearrowleft \circlearrowright \looparrowleft \looparrowright`,
	`\twoheadleftarrow \twoheadrightarrow \leftarrowtail \rightarrowtail \rightsquigarrow \leadsto`,
	`\nleftarrow \nrightarrow \nLeftarrow \nRightarrow \nleftrightarrow \nLeftrightarrow`,
	`\dashrightarrow \dashleftarrow \Lleftarrow \Rrightarrow \Lsh \Rsh \multimap`,
	`\upharpoonleft \upharpoonright \downharpoonleft \downharpoonright \leftharpoonup \leftharpoondown`,
	`\rightrightarrows \leftleftarrows \rightleftarrows \leftrightarrows \upuparrows \downdownarrows`,
	`\between \pitchfork \eqcirc \circeq \bumpeq \Bumpeq \doteq \doteqdot \triangleq`,
	`\smile \frown \bowtie \Join \asymp \backsim \backsimeq \eqsim`,
	`\complement \eth \Finv \Game \Bbbk \mho \imath \jmath \surd`,
	`\flat \natural \sharp \maltese \yen \pounds \copyright \circledR \circledS \S \P`,
	`\lozenge \blacklozenge \blacksquare \blacktriangle \blacktriangledown \bigstar`,
	`\diagup \diagdown \backprime \sphericalangle \intercal \barwedge \veebar`,
	`\R \N \Z \Q \C \reals \natnums \Complex \infin \isin \plusmn \larr \rArr \Harr`,
	`\nsubseteq \nsupseteq \nsubset \notni \npreceq \nsucc \nparallel \nshortmid`,
	`\colon \vdots \iddots \cdotp \ldotp`,
	`\iiiint \oiint \oiiint \fint`,
	`\And \lt \gt`,
	`\mho \Omega \omega`,
	`x' \quad x'' \quad x''' \quad x^{\prime\prime}`,
	`x'_1 \quad x_1' \quad x'^2`,

	// Unicode input.
	`α + β = γ`,
	`x² + y² = z²`,
	`∀ε>0 ∃δ>0`,
	`∑_{i=1}^n xᵢ`,
	`A ⊆ B ∪ C`,
	`f: ℝ → ℝ`,
	`√2 ≈ 1.414`,
	`x ≤ y ≥ z ≠ w`,
	`∫₀¹ f(x) dx`,
	`ψ(x,t) = ⟨x|ψ(t)⟩`,
	`αβγ`,
	`x̂ ŷ`,
	`a·b`,
	`a×b÷c`,
	`⌊x⌋ + ⌈y⌉`,
	`‖v‖`,
	`ℏω`,
	`x ∈ ℕ`,
	`∞`,
	`ä ö ü`,
	`日本`,
	`😀`,
	`\frac{⟨a⟩}{⌊b}`,

	// Typst-sensitive characters.
	`a // b`,
	`a /* b */ c`,
	`a \# b`,
	`\text{a # b}`,
	`a @ b`,
	`x"y`,
	"a ` b",
	`a <= b >= c`,
	`a -> b => c`,
	`a := b`,
	`a ... b`,
	`a || b`,
	`[| x |]`,
	`a << b >> c`,
	`a !== b`,
	`f(x) = x.y`,
	`\alpha.\beta`,
	`x.5`,
	`1.2.3`,
	`a;b`,
	`\frac{a;b}{c:d}`,
	`\frac{a,b}{c}`,
	`\sqrt{a, b}`,
	`\text{a"b\textbackslash c}`,
	`\$ \% \& \_ \{ \}`,
	`x_\$`,
	`a\\b`,
	`\textdollar`,
	`\hspace{1em}.`,
	`\hspace{1em};`,
	`\boxed{x}.`,
	`\phantom{x};`,
	`a \text{b} . c`,
	`u\{`,
	`\u{1F600}`,
	`a^{b}_{c}`,
	`a_{b}^{c}`,
	`^2`,
	`_2 x`,
	`'`,
	`x^`,
	`x_`,
	`x^^2`,
	`x^2^3`,
	`x_1_2`,
	`x^{}`,
	`{}`,
	`{{{{x}}}}`,
	`{=}`,
	`a{+}b`,
	`{a+b}^2`,
	`{a \over b}`,
	`a \over b \over c`,
	`{n \atop k}`,
	`{n \brack k}`,
	`{n \brace k}`,

	// Malformed input.
	`\frac{a}{`,
	`\frac{a}`,
	`\frac`,
	`\sqrt`,
	`\sqrt[3`,
	`\left( x`,
	`x \right)`,
	`\left( x \right`,
	`\middle|`,
	`\begin{pmatrix} a & b`,
	`\end{pmatrix}`,
	`\begin{foo} a & b \\ c & d \end{foo}`,
	`\begin{pmatrix} a \end{bmatrix}`,
	`x}`,
	`{x`,
	`}}}{{{`,
	`\`,
	`a \`,
	`\\`,
	`\\ a \\`,
	`&`,
	`a & b`,
	`\frac{a & b}{c}`,
	`\unknowncommand{x}`,
	`\foo \bar`,
	`\text{unclosed`,
	`\text`,
	`\operatorname{}`,
	`\mathbb{}`,
	`\hspace{}`,
	`\hspace{abc}`,
	`\color{nosuchcolor} x`,
	`\textcolor{}{x}`,
	`\label{a}\label{b} x`,
	`\tag{3} x`,
	`x \nonumber`,
	`\not`,
	`\not\subseteq`,
	`\not\preceq`,
	`\not\alpha`,
	`\overbrace{x}`,
	`\underbrace{x}^{y}`,
	`\xrightarrow{}`,
	`\xrightarrow`,
	`\big`,
	`\left`,
	`\begin`,
	`\begin{}`,
	`\end`,
	`\begin{array}{} a \end{array}`,
	`\begin{array} a \end{array}`,
	`\begin{array}{c|} a \\ \hline \end{array}`,
	`\begin{array}{*{40}{c}} a \end{array}`,
	`\begin{cases} \end{cases}`,
	`\begin{matrix}\end{matrix}`,
	`\begin{aligned}\end{aligned}`,
	`\begin{align}\end{align}`,
	`\sideset{_a^b}{_c^d}\sum`,
	`\prescript{14}{6}{\mathrm{C}}`,
	`\unicode{x2208}`,
	`\unicode{xZZ}`,
	`\newcommand{\R}{\mathbb{R}} x \in \R`,
	`\def\x{y} \x`,
	`\mathchoice{a}{b}{c}{d}`,
	`\cancelto{0}{x}`,
	`\genfrac`,
	`%comment only`,
	`a % comment
	+ b`,
	"x\ty\nz",
	"\x00\x01x",
	"\xff\xfe",
	"",
	`   `,
	`\displaystyle`,
	`\limits`,
	`\sum\limits`,
	`x\limits^2`,
	`\int\nolimits_0^1`,
	`\lim\nolimits_{x}`,
	`\displaystyle{\sum}`,
	`\boxed`,
	`\substack{a}`,
	`\substack{a \\ b \\}`,
	`\dots +`,
	`a + \dots + b`,
	`a, \dots, b`,
	`\int \dots \int`,
	`\mathrm{\alpha}`,
	`\mathbb{R}^{n \times n}`,
	`\mathbb{Rx}`,
	`\Bbb{Z}`,
	`\mathcal{O}(n^2)`,
	`\pmod`,
	`\left\{ \begin{matrix} a \\ b \end{matrix} \right.`,
	`\begin{pmatrix} \begin{pmatrix} a \end{pmatrix} & b \end{pmatrix}`,
	`\begin{cases} \begin{cases} a \end{cases} \end{cases}`,
	`\frac{\begin{aligned} a &= b \\ c &= d \end{aligned}}{2}`,
	`\sqrt{\begin{matrix} a \\ b \end{matrix}}`,
	`\left( \begin{aligned} a &= b \\ c &= d \end{aligned} \right)`,
	`\begin{aligned} a &= b \end{aligned} + \begin{aligned} c &= d \end{aligned}`,
	`\text{$\frac{a}{b}$ and \(x^2\)}`,
	`\text{\textit{a \textbf{b}}}`,
	`\textbf{\textit{x}}`,
	`\operatorname{arg\,max}`,
	`\operatorname{\mathrm{tr}}`,
	`\vec{\imath}`,
	`\hat{\jmath}`,
	`\dot{\vec{x}}`,
	`\vec{\vec{x}}`,
	`\hat{}`,
	`\tilde`,
	`a\big)`,
	`\Biggr]`,
	`x^{\left( n \right)}`,
	`\frac{1}{\left( x \right)}`,
	`x_{\left[ 1 \right]}`,
	`\overset{!}{=}`,
	`\overset{\text{def}}{=}`,
	`\underset{x \to 0}{\lim}`,
	`\stackrel{\mathrm{def}}{=}`,
	`a \xrightarrow{f} b \xrightarrow{g} c`,
	`\xLeftrightarrow[below]{above}`,
	`\xmapsto{f}`,
	`\xlongequal{\text{def}}`,
	`\tfrac12`,
	`\frac12`,
	`\frac\alpha\beta`,
	`\frac 1 2`,
	`\sqrt2`,
	`x^\frac12`,
	`x_\mathrm{max}`,
	`x^\alpha_\beta`,
	`a^{b^{c^{d^{e}}}}`,
	`x_{a_{b_{c}}}`,
	`\sum_{i=1}^{n}\sum_{j=1}^{m}a_{ij}`,
	`\int_0^\infty\!\!\int_0^\infty e^{-(x^2+y^2)}\,dx\,dy`,
}
